version: "3.8"

services:
  elasticsearch_1:
    container_name: "elasticsearch_1"
    image: elasticsearch:7.5.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana_1:
    container_name: "kibana_1"
    image: kibana:7.5.2
    ports: 
      - 5601:5601
    environment: 
      ELASTICSEARCH_HOSTS: http://elasticsearch_1:9200
    
  mongo_1:
    container_name: "mongo_1"
    image: mongo:latest
    ports:
      - 27017:27017

  rabbitmq_1:
    container_name: "rabbitmq_1"
    image: rabbitmq:latest
    ports:
      - 5672:5672
    hostname: my-rabbit
